spring:
  application:
    name: walter-multimodule-training-boot
  data:
    mongodb:
      database: walter-multimodule-training
      host: localhost
      port: 23000
server:
  port: 8080
logging:
  level:
    org:
      springframework: DEBUG
      springdoc: DEBUG




