spring:
  application:
    admin:
      name: walter-multimodule-training-boot
  datasource:
    url: jdbc:h2:file:./data/testdb
    driver-class-name: org.h2.Driver
    username: root
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
  h2:
    console:
      enabled: true
      path: /h2-console
server:
  port: 8080
logging:
  level:
    org:
      springdoc: DEBUG



